version: '3.8'

services:
  node_app:
    build: ./otros/servicio/.
    ports:
      - "3000:3000"

  mariadb:
    image: mariadb
    command: --default-authentication-plugin=ey%2024#database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ey%2024#database
      MYSQL_DATABASE: admin
      MYSQL_USER: eyuser
      MYSQL_PASSWORD: passwordey1234
    ports:
      - "3310:3306"
    volumes:
      - ./volumenes/mariadb_data:/var/lib/mysql
      - ./volumenes/initDB.sql:/docker-entrypoint-initdb.d/1.sql  # Montar el directorio con los archivos SQL

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: eyuserroot
      MONGO_INITDB_ROOT_PASSWORD: passwordey1234
      MONGO_INITDB_DATABASE: root-db
    ports:
        - "27017:27017"
    volumes:
        - ./volumenes/mongodb_data:/data/db       
        - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      
  ms-personas:
    depends_on:
        - kafka
        - mariadb
    build: ./otros/ms-personas/.
    container_name: ms-personas
    restart: always
    ports:
      - "8173:8173"
      
  ms-cuentas:
    depends_on:
        - kafka
        - mariadb
    build: ./otros/ms-cuentas/.
    container_name: ms-cuentas
    restart: always
    ports:
      - "8175:8175"

volumes:
  mariadb_data:
  mongodb_data: